* Leetcode: Teemo Attacking                                     :BLOG:Medium:
#+STARTUP: showeverything
#+OPTIONS: toc:nil \n:t ^:nil creator:nil d:nil
:PROPERTIES:
:type:     game, interval, manydetails, classic
:END:
---------------------------------------------------------------------
Teemo Attacking
---------------------------------------------------------------------
Similar Problems:
- [[https://code.dennyzhang.com/merge-intervals][Merge Intervals]]
- [[https://code.dennyzhang.com/review-interval][Review: Interval Problems]]
- Tag: [[https://code.dennyzhang.com/tag/interval][#interval]], [[https://code.dennyzhang.com/tag/game][#game]], [[https://code.dennyzhang.com/tag/manydetails][#manydetails]], [[https://code.dennyzhang.com/tag/classic][#classic]]
---------------------------------------------------------------------
In LOL world, there is a hero called Teemo and his attacking can make his enemy Ashe be in poisoned condition. Now, given the Teemo's attacking ascending time series towards Ashe and the poisoning time duration per Teemo's attacking, you need to output the total time that Ashe is in poisoned condition.

You may assume that Teemo attacks at the very beginning of a specific time point, and makes Ashe be in poisoned condition immediately.

Example 1:
#+BEGIN_EXAMPLE
Input: [1,4], 2
Output: 4
Explanation: At time point 1, Teemo starts attacking Ashe and makes Ashe be poisoned immediately. 
This poisoned status will last 2 seconds until the end of time point 2. 
And at time point 4, Teemo attacks Ashe again, and causes Ashe to be in poisoned status for another 2 seconds. 
So you finally need to output 4.
#+END_EXAMPLE

Example 2:
#+BEGIN_EXAMPLE
Input: [1,2], 2
Output: 3
Explanation: At time point 1, Teemo starts attacking Ashe and makes Ashe be poisoned. 
This poisoned status will last 2 seconds until the end of time point 2. 
However, at the beginning of time point 2, Teemo attacks Ashe again who is already in poisoned status. 
Since the poisoned status won't add up together, though the second poisoning attack will still work at time point 2, it will stop at the end of time point 3. 
So you finally need to output 3.
#+END_EXAMPLE

Note:
1. You may assume the length of given time series array won't exceed 10000.
- You may assume the numbers in the Teemo's attacking time series and his poisoning time duration per attacking are non-negative integers, which won't exceed 10,000,000.

Github: [[url-external:https://github.com/DennyZhang/challenges-leetcode-interesting/tree/master/teemo-attacking][challenges-leetcode-interesting]]

Credits To: [[url-external:https://leetcode.com/problems/teemo-attacking/description/][leetcode.com]]

Leave me comments, if you have better ways to solve.

#+BEGIN_SRC go
// Blog link: https://code.dennyzhang.com/teemo-attacking
// Basic Ideas: Merge Intervals
//  Test cases:
//   Empty list, list with one item, overlapped or not
// About Intervals: which one you will choose: [start, end], or [start, end)?
//
// Complexity: Time O(n), Space O(1)
func findPoisonedDuration(timeSeries []int, duration int) int {
  if len(timeSeries) == 0 { return 0 }
  res := 0
  start, end := 0, 0
  for i, time := range timeSeries {
    if i == 0 {
      start, end = time, time+duration-1
      continue
    }
    if time > end {
      // not overlapped
      res += end-start+1
      start, end = time, time+duration-1
    } else {
      // overlapped
      end = time+duration-1
    }
  }
  // collect the last interval
  res += end-start+1
  return res
}
#+END_SRC
