* Leetcode: Split Linked List in Parts                                              :BLOG:Medium:
#+STARTUP: showeverything
#+OPTIONS: toc:nil \n:t ^:nil creator:nil d:nil
:PROPERTIES:
:type:     #linkedlist
:END:
---------------------------------------------------------------------
Split Linked List in Parts
---------------------------------------------------------------------
Given a (singly) linked list with head node root, write a function to split the linked list into k consecutive linked list "parts".

The length of each part should be as equal as possible: no two parts should have a size differing by more than 1. This may lead to some parts being null.

The parts should be in order of occurrence in the input list, and parts occurring earlier should always have a size greater than or equal parts occurring later.

Return a List of ListNode's representing the linked list parts that are formed.
#+BEGIN_EXAMPLE

Examples 1->2->3->4, k = 5 // 5 equal parts [ [1], [2], [3], [4], null ]
Example 1:
Input: 
root = [1, 2, 3], k = 5
Output: [[1],[2],[3],[],[]]
Explanation:
The input and each element of the output are ListNodes, not arrays.
For example, the input root has root.val = 1, root.next.val = 2, \root.next.next.val = 3, and root.next.next.next = null.
The first element output[0] has output[0].val = 1, output[0].next = null.
The last element output[4] is null, but it's string representation as a ListNode is [].
#+END_EXAMPLE

#+BEGIN_EXAMPLE
Example 2:
Input: 
root = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], k = 3
Output: [[1, 2, 3, 4], [5, 6, 7], [8, 9, 10]]
Explanation:
The input has been split into consecutive parts with size difference at most 1, and earlier parts are a larger size than the later parts.
#+END_EXAMPLE

Note:

- The length of root will be in the range [0, 1000].
- Each value of a node in the input will be an integer in the range [0, 999].
- k will be an integer in the range [1, 50].

Github: [[url-external:https://github.com/DennyZhang/challenges-leetcode-interesting/tree/master/split-linked-list-in-parts][challenges-leetcode-interesting]]

Credits To: [[url-external:https://leetcode.com/problems/split-linked-list-in-parts/description/][leetcode.com]]

Leave me comments, if you have better ways to solve.

#+BEGIN_SRC python
## Blog link: https://brain.dennyzhang.com/split-linked-list-in-parts
class Solution(object):
    def splitListToParts(self, root, k):
        """
        :type root: ListNode
        :type k: int
        :rtype: List[ListNode]
        """
        # get size of the link
        count = 0
        p = root
        while p:
            count += 1
            p = p.next
        part_size = count / k
        remaining = count % k

        res = []
        p = root
        for i in xrange(k):
            dummy_node = ListNode(None)
            q = dummy_node

            if remaining != 0:
                tmp = ListNode(p.val)
                q.next = tmp
                q = tmp
                p = p.next
                remaining -= 1

            for j in xrange(part_size):
                tmp = ListNode(p.val)
                q.next = tmp
                q = tmp
                p = p.next
            res.append(dummy_node.next)

        return res
#+END_SRC
