* Leetcode: Kill Process                                         :BLOG:Medium:
#+STARTUP: showeverything
#+OPTIONS: toc:nil \n:t ^:nil creator:nil d:nil
:PROPERTIES:
:type:     hashmap, queue, inspiring
:END:
---------------------------------------------------------------------
Kill Process
---------------------------------------------------------------------
Similar Problems:
- Tag: [[https://code.dennyzhang.com/tag/hashmap][#hashmap]]
---------------------------------------------------------------------

Given n processes, each process has a unique PID (process id) and its PPID (parent process id).

Each process only has one parent process, but may have one or more children processes. This is just like a tree structure. Only one process has PPID that is 0, which means this process has no parent process. All the PIDs will be distinct positive integers.

We use two list of integers to represent a list of processes, where the first list contains PID for each process and the second list contains the corresponding PPID.

Now given the two lists, and a PID representing a process you want to kill, return a list of PIDs of processes that will be killed in the end. You should assume that when a process is killed, all its children processes will be killed. No order is required for the final answer.

Example 1:
#+BEGIN_EXAMPLE
Input: 
pid =  [1, 3, 10, 5]
ppid = [3, 0, 5, 3]
kill = 5
Output: [5,10]
Explanation: 
           3
         /   \
        1     5
             /
            10
Kill 5 will also kill 10.
#+END_EXAMPLE

Note:

1. The given kill id is guaranteed to be one of the given PIDs.
- n >= 1.

Github: [[url-external:https://github.com/DennyZhang/challenges-leetcode-interesting/tree/master/kill-process][challenges-leetcode-interesting]]

Credits To: [[url-external:https://leetcode.com/problems/kill-process/description/][leetcode.com]]

Leave me comments, if you have better ways to solve.

#+BEGIN_SRC python
## Blog link: https://code.dennyzhang.com/kill-process
## Basic Ideas: hashmap
##    Find children by id
##
## Complexity: Time O(n), Space O(n)
class Solution:
    def killProcess(self, pid, ppid, kill):
        """
        :type pid: List[int]
        :type ppid: List[int]
        :type kill: int
        :rtype: List[int]
        """
        import collections
        d = collections.defaultdict(lambda: [])
        for i in range(len(pid)):
            p, q = pid[i], ppid[i]
            d[q].append(p)

        queue = collections.deque()
        queue.append(kill)
        res = [kill]
        while len(queue) != 0:
            for k in range(len(queue)):
                q = queue.popleft()
                for p in d[q]:
                    res.append(p)
                    queue.append(p)
        return res
#+END_SRC
