* Leetcode: Valid Tic-Tac-Toe State                              :BLOG:Hard:
#+STARTUP: showeverything
#+OPTIONS: toc:nil \n:t ^:nil creator:nil d:nil
:PROPERTIES:
:type:     misc
:END:
---------------------------------------------------------------------
Valid Tic-Tac-Toe State
---------------------------------------------------------------------
A Tic-Tac-Toe board is given as a string array board. Return True if and only if it is possible to reach this board position during the course of a valid tic-tac-toe game.

The board is a 3 x 3 array, and consists of characters " ", "X", and "O".  The " " character represents an empty square.

Here are the rules of Tic-Tac-Toe:

- Players take turns placing characters into empty squares (" ").
- The first player always places "X" characters, while the second player always places "O" characters.
- "X" and "O" characters are always placed into empty squares, never filled ones.
- The game ends when there are 3 of the same (non-empty) character filling any row, column, or diagonal.
- The game also ends if all squares are non-empty.
- No more moves can be played if the game is over.

#+BEGIN_EXAMPLE
Example 1:
Input: board = ["O  ", "   ", "   "]
Output: false
Explanation: The first player always plays "X".
#+END_EXAMPLE

#+BEGIN_EXAMPLE
Example 2:
Input: board = ["XOX", " X ", "   "]
Output: false
Explanation: Players take turns making moves.
#+END_EXAMPLE

#+BEGIN_EXAMPLE
Example 3:
Input: board = ["XXX", "   ", "OOO"]
Output: false
#+END_EXAMPLE

#+BEGIN_EXAMPLE
Example 4:
Input: board = ["XOX", "O O", "XOX"]
Output: true
#+END_EXAMPLE

Note:

- board is a length-3 array of strings, where each string board[i] has length 3.
- Each board[i][j] is a character in the set {" ", "X", "O"}.

Github: [[url-external:https://github.com/DennyZhang/challenges-leetcode-interesting/tree/master/valid-tic-tac-toe-state][challenges-leetcode-interesting]]

Credits To: [[url-external:https://leetcode.com/problems/valid-tic-tac-toe-state/description/][leetcode.com]]

Leave me comments, if you have better ways to solve.

#+BEGIN_SRC python
## Blog link: https://brain.dennyzhang.com/valid-tic-tac-toe-state

#+END_SRC
