* Leetcode: Ternary Expression Parser                           :BLOG:Medium:
#+STARTUP: showeverything
#+OPTIONS: toc:nil \n:t ^:nil creator:nil d:nil
:PROPERTIES:
:type:     dfs, stack
:END:
---------------------------------------------------------------------
Ternary Expression Parser
---------------------------------------------------------------------
Similar Problems:
- Tag: [[https://brain.dennyzhang.com/tag/dfs][#dfs]], [[https://brain.dennyzhang.com/tag/stack][#stack]]
---------------------------------------------------------------------

Given a string representing arbitrarily nested ternary expressions, calculate the result of the expression. You can always assume that the given expression is valid and only consists of digits 0-9, ?, :, T and F (T and F represent True and False respectively).

Note:

1. The length of the given string is <= 10000.
- Each number will contain only one digit.
- The conditional expressions group right-to-left (as usual in most languages).
- The condition will always be either T or F. That is, the condition will never be a digit.
- The result of the expression will always evaluate to either a digit 0-9, T or F.

Example 1:
#+BEGIN_EXAMPLE
Input: "T?2:3"

Output: "2"

Explanation: If true, then result is 2; otherwise result is 3.
#+END_EXAMPLE

Example 2:
#+BEGIN_EXAMPLE
Input: "F?1:T?4:5"

Output: "4"

Explanation: The conditional expressions group right-to-left. Using parenthesis, it is read/evaluated as:

    "(F ? 1 : (T ? 4 : 5))"          "(F ? 1 : (T ? 4 : 5))"
 -> "(F ? 1 : 4)"            or   -> "(T ? 4 : 5)"
 -> "4"                           -> "4"
#+END_EXAMPLE

Example 3:
#+BEGIN_EXAMPLE
Input: "T?T?F:5:3"

Output: "F"

Explanation: The conditional expressions group right-to-left. Using parenthesis, it is read/evaluated as:

    "(T ? (T ? F : 5) : 3)"        "(T ? (T ? F : 5) : 3)"
 -> "(T ? F : 3)"           or  -> "(T ? F : 5)"
 -> "F"                         -> "F"
#+END_EXAMPLE

Github: [[url-external:https://github.com/DennyZhang/challenges-leetcode-interesting/tree/master/ternary-expression-parser][challenges-leetcode-interesting]]

Credits To: [[url-external:https://leetcode.com/problems/ternary-expression-parser/description/][leetcode.com]]

Leave me comments, if you have better ways to solve.

#+BEGIN_SRC go
// Blog link: https://brain.dennyzhang.com/ternary-expression-parser

#+END_SRC
