* Leetcode: Bulls and Cows                                       :BLOG:Basic:
#+STARTUP: showeverything
#+OPTIONS: toc:nil \n:t ^:nil creator:nil d:nil
:PROPERTIES:
:type:     game, string
:END:
---------------------------------------------------------------------
Bulls and Cows
---------------------------------------------------------------------
Similar Problems:
- Tag: [[https://code.dennyzhang.com/tag/game][#game]], [[https://code.dennyzhang.com/tag/string][#string]]
---------------------------------------------------------------------
You are playing the following [[url-external:https://en.wikipedia.org/wiki/Bulls_and_Cows][Bulls and Cows game]] with your friend: You write down a number and ask your friend to guess what the number is. Each time your friend makes a guess, you provide a hint that indicates how many digits in said guess match your secret number exactly in both digit and position (called "bulls") and how many digits match the secret number but locate in the wrong position (called "cows"). Your friend will use successive guesses and hints to eventually derive the secret number.

For example:
#+BEGIN_EXAMPLE
Secret number:  "1807"
Friend's guess: "7810"
#+END_EXAMPLE

Hint: 1 bull and 3 cows. (The bull is 8, the cows are 0, 1 and 7.)
Write a function to return a hint according to the secret number and friend's guess, use A to indicate the bulls and B to indicate the cows. In the above example, your function should return "1A3B".

Please note that both secret number and friend's guess may contain duplicate digits, for example:
#+BEGIN_EXAMPLE
Secret number:  "1123"
Friend's guess: "0111"
#+END_EXAMPLE

In this case, the 1st 1 in friend's guess is a bull, the 2nd or 3rd 1 is a cow, and your function should return "1A1B".
You may assume that the secret number and your friend's guess only contain digits, and their lengths are always equal.

Github: [[url-external:https://github.com/DennyZhang/challenges-leetcode-interesting/tree/master/bulls-and-cows][challenges-leetcode-interesting]]

Credits To: [[url-external:https://leetcode.com/problems/bulls-and-cows/description/][leetcode.com]]

Leave me comments, if you have better ways to solve.

- Solution: 2 arrays with 10 elements
#+BEGIN_SRC go
// Blog link: https://code.dennyzhang.com/bulls-and-cows
// Basic Ideas: 2 arrays
// Complexity: Time O(n), Space O(1)
func getHint(secret string, guess string) string {
    secret_list := [10]int{}
    guess_list := [10]int{}
    bulls, cows := 0, 0
    for i, _ := range secret {
        if secret[i] == guess[i] {
            bulls += 1
        } else {
            secret_list[int(secret[i]-'0')] += 1
            guess_list[int(guess[i]-'0')] += 1
        }
    }
    for i:= 0; i<10; i++ {
        if secret_list[i] < guess_list[i] {
            cows += secret_list[i]
        } else {
            cows += guess_list[i]
        }
    }
    return fmt.Sprintf("%dA%dB", bulls, cows)
}
#+END_SRC
