* Leetcode: Valid Parenthesis String                           :BLOG:Amusing:
#+STARTUP: showeverything
#+OPTIONS: toc:nil \n:t ^:nil creator:nil d:nil
:PROPERTIES:
:type:     parentheses, string
:END:
---------------------------------------------------------------------
Valid Parenthesis String
---------------------------------------------------------------------
Similar Problems:
- Tag: [[https://brain.dennyzhang.com/category/basic][#basic]]
---------------------------------------------------------------------
Given a string containing only three types of characters: '(', ')' and '*', write a function to check whether this string is valid. We define the validity of a string by these rules:

Any left parenthesis '(' must have a corresponding right parenthesis ')'.
Any right parenthesis ')' must have a corresponding left parenthesis '('.
Left parenthesis '(' must go before the corresponding right parenthesis ')'.
'*' could be treated as a single right parenthesis ')' or a single left parenthesis '(' or an empty string.
An empty string is also valid.

Example 1:
#+BEGIN_EXAMPLE
Input: "()"
Output: True
#+END_EXAMPLE

Example 2:
#+BEGIN_EXAMPLE
Input: "(*)"
Output: True
#+END_EXAMPLE

Example 3:
#+BEGIN_EXAMPLE
Input: "(*))"
Output: True
#+END_EXAMPLE

Note:
- The string size will be in the range [1, 100].

Github: [[url-external:https://github.com/DennyZhang/challenges-leetcode-interesting/tree/master/valid-parenthesis-string][challenges-leetcode-interesting]]

Credits To: [[url-external:https://leetcode.com/problems/valid-parenthesis-string/description/][leetcode.com]]

Leave me comments, if you have better ways to solve.

#+BEGIN_SRC python
## Blog link: https://brain.dennyzhang.com/valid-parenthesis-string

#+END_SRC
