* Leetcode: Text Justification                                   :BLOG:Hard:
#+STARTUP: showeverything
#+OPTIONS: toc:nil \n:t ^:nil creator:nil d:nil
:PROPERTIES:
:type:     string, classic
:END:
---------------------------------------------------------------------
Text Justification
---------------------------------------------------------------------
Similar Problems:
- Tag: [[https://code.dennyzhang.com/tag/string][#string]]
---------------------------------------------------------------------
Given an array of words and a length L, format the text such that each line has exactly L characters and is fully (left and right) justified.

You should pack your words in a greedy approach; that is, pack as many words as you can in each line. Pad extra spaces ' ' when necessary so that each line has exactly L characters.

Extra spaces between words should be distributed as evenly as possible. If the number of spaces on a line do not divide evenly between words, the empty slots on the left will be assigned more spaces than the slots on the right.

For the last line of text, it should be left justified and no extra space is inserted between words.

For example,
#+BEGIN_EXAMPLE
words: ["This", "is", "an", "example", "of", "text", "justification."]
L: 16.
#+END_EXAMPLE

Return the formatted lines as:
#+BEGIN_EXAMPLE
[
   "This    is    an",
   "example  of text",
   "justification.  "
]
#+END_EXAMPLE

Note: Each word is guaranteed not to exceed L in length.

Github: [[url-external:https://github.com/DennyZhang/challenges-leetcode-interesting/tree/master/text-justification][challenges-leetcode-interesting]]

Credits To: [[url-external:https://leetcode.com/problems/text-justification/description/][leetcode.com]]

Leave me comments, if you have better ways to solve.

#+BEGIN_SRC python
## Blog link: https://code.dennyzhang.com/text-justification
#+END_SRC
