* Leetcode: Friend Requests II: Who Has the Most Friends                                              :BLOG:Medium:
#+STARTUP: showeverything
#+OPTIONS: toc:nil \n:t ^:nil creator:nil d:nil
:PROPERTIES:
:type:     sql
:END:
---------------------------------------------------------------------
Friend Requests II: Who Has the Most Friends
---------------------------------------------------------------------
Similar Problems:
- [[https://brain.dennyzhang.com/friend-requests-i-overall-acceptance-rate][Friend Requests I: Overall Acceptance Rate]]
- [[https://brain.dennyzhang.com/review-sql][Review: SQL Problems]]
---------------------------------------------------------------------
In social network like Facebook or Twitter, people send friend requests and accept others' requests as well.
Table request_accepted holds the data of friend acceptance, while requester_id and accepter_id both are the id of a person.
#+BEGIN_EXAMPLE
| requester_id | accepter_id | accept_date|
|--------------|-------------|------------|
| 1            | 2           | 2016_06-03 |
| 1            | 3           | 2016-06-08 |
| 2            | 3           | 2016-06-08 |
| 3            | 4           | 2016-06-09 |
#+END_EXAMPLE

Write a query to find the the people who has most friends and the most friends number. For the sample data above, the result is:
#+BEGIN_EXAMPLE
| id | num |
|----|-----|
| 3  | 3   |
#+END_EXAMPLE

Note:
- It is guaranteed there is only 1 people having the most friends.
- The friend request could only been accepted once, which mean there is no multiple records with the same requester_id and accepter_id value.

Explanation:
The person with id '3' is a friend of people '1', '2' and '4', so he has 3 friends in total, which is the most number than any others.

Follow-up:
In the real world, multiple people could have the same most number of friends, can you find all these people in this case?

Github: [[url-external:https://github.com/DennyZhang/challenges-leetcode-interesting/tree/master/friend-requests-ii-who-has-the-most-friends][challenges-leetcode-interesting]]

Credits To: [[url-external:https://leetcode.com/problems/friend-requests-ii-who-has-the-most-friends/description/][leetcode.com]]

Leave me comments, if you have better ways to solve.

#+BEGIN_SRC python
## Blog link: https://brain.dennyzhang.com/friend-requests-ii-who-has-the-most-friends
select t.id, sum(t.num) as num
from (
      (select requester_id as id, count(1) as num
       from request_accepted
       group by requester_id)
      union all
       (select accepter_id as id, count(1) as num
        from request_accepted
        group by accepter_id)) as t
group by t.id
order by num desc
limit 1
#+END_SRC
