* Leetcode: Chalkboard XOR Game                                   :BLOG:Hard:
#+STARTUP: showeverything
#+OPTIONS: toc:nil \n:t ^:nil creator:nil d:nil
:PROPERTIES:
:type:     game, math, bitmanipulation, redo
:END:
---------------------------------------------------------------------
Chalkboard XOR Game
---------------------------------------------------------------------
Similar Problems:
- [[https://brain.dennyzhang.com/review-math][Review: Math Problems]]
- Tag: [[https://brain.dennyzhang.com/tag/bitmanipulation][#bitmanipulation]], [[https://brain.dennyzhang.com/tag/game][#game]], [[https://brain.dennyzhang.com/tag/math][#math]]
---------------------------------------------------------------------
We are given non-negative integers nums[i] which are written on a chalkboard.  Alice and Bob take turns erasing exactly one number from the chalkboard, with Alice starting first.  If erasing a number causes the bitwise XOR of all the elements of the chalkboard to become 0, then that player loses.  (Also, we'll say the bitwise XOR of one element is that element itself, and the bitwise XOR of no elements is 0.)

Also, if any player starts their turn with the bitwise XOR of all the elements of the chalkboard equal to 0, then that player wins.

Return True if and only if Alice wins the game, assuming both players play optimally.

Example:
#+BEGIN_EXAMPLE
Input: nums = [1, 1, 2]
Output: false
Explanation: 
Alice has two choices: erase 1 or erase 2. 
If she erases 1, the nums array becomes [1, 2]. The bitwise XOR of all the elements of the chalkboard is 1 XOR 2 = 3. Now Bob can remove any element he wants, because Alice will be the one to erase the last element and she will lose. 
If Alice erases 2 first, now nums becomes [1, 1]. The bitwise XOR of all the elements of the chalkboard is 1 XOR 1 = 0. Alice will lose.
#+END_EXAMPLE

Notes:

- 1 <= N <= 1000. 
- 0 <= nums[i] <= 2^16.

Github: [[url-external:https://github.com/DennyZhang/challenges-leetcode-interesting/tree/master/chalkboard-xor-game][challenges-leetcode-interesting]]

Credits To: [[url-external:https://leetcode.com/problems/chalkboard-xor-game/description/][leetcode.com]]

Leave me comments, if you have better ways to solve.

#+BEGIN_SRC python
## Blog link: https://brain.dennyzhang.com/chalkboard-xor-game

#+END_SRC
