* Leetcode: Number of Distinct Islands                           :BLOG:Medium:
#+STARTUP: showeverything
#+OPTIONS: toc:nil \n:t ^:nil creator:nil d:nil
:PROPERTIES:
:type:     graph
:END:
---------------------------------------------------------------------
Number of Distinct Islands
---------------------------------------------------------------------
Similar Problems:
- [[https://code.dennyzhang.com/number-of-distinct-islands-ii][Number of Distinct Islands II]]
- Tag: [[https://code.dennyzhang.com/tag/graph][#graph]]
---------------------------------------------------------------------
Given a non-empty 2D array grid of 0's and 1's, an island is a group of 1's (representing land) connected 4-directionally (horizontal or vertical.) You may assume all four edges of the grid are surrounded by water.

Count the number of distinct islands. An island is considered to be the same as another if and only if one island can be translated (and not rotated or reflected) to equal the other.

Example 1:
#+BEGIN_EXAMPLE
11000
11000
00011
00011
Given the above grid map, return 1.
#+END_EXAMPLE

Example 2:
#+BEGIN_EXAMPLE
11011
10000
00001
11011
Given the above grid map, return 3.
#+END_EXAMPLE

Notice that:
#+BEGIN_EXAMPLE
11
1
#+END_EXAMPLE

and
#+BEGIN_EXAMPLE
 1
11
#+END_EXAMPLE
are considered different island shapes, because we do not consider reflection / rotation.
Note: The length of each dimension in the given grid does not exceed 50.

Github: [[url-external:https://github.com/DennyZhang/challenges-leetcode-interesting/tree/master/number-of-distinct-islands][challenges-leetcode-interesting]]

Credits To: [[url-external:https://leetcode.com/problems/number-of-distinct-islands/description/][leetcode.com]]

Leave me comments, if you have better ways to solve.

#+BEGIN_SRC go
// Blog link: https://code.dennyzhang.com/number-of-distinct-islands

#+END_SRC
